### ISSUE TITLE
Fails to backup with Nexus 6 

### ISSUE THREAD

**Issue by cbluth** [dlenski/tetherback#44] opened 2017-02-13 22:47 UTC
```
user@linux:~/Temp/android-backup$ tetherback 
tetherback v0.9.1
Found ADB version 1.0.32
Using default transfer method: adb exec-out pipe (--exec-out)
Device reports kernel 3.10.40-gee46fae
Device reports TWRP version 3.0.3-0
Reading partition map for mmcblk0 (42 partitions)...
  partition map: 100%                                                                                                                                        
Reading partition map for mmcblk0rpmb (0 partitions)...
  partition map: 100%                                                                                                                                        
Saving backup images in ./twrp-backup-2017-02-13--16-25-08/ ...
Saving partition boot (mmcblk0p37), 16 MiB uncompressed...
  boot.emmc.win: 100%   3.9 MiB/s   8.6 MiB                                                                                                                  
Saving tarball of mmcblk0p41 (mounted at /system), 2048 MiB uncompressed...
  system.ext4.win: 100%   5.2 MiB/s 750.9 MiB                                                                                                                
Traceback (most recent call last):
  File "/usr/local/bin/tetherback", line 11, in <module>
    load_entry_point('tetherback==0.9.1', 'console_scripts', 'tetherback')()
  File "/usr/local/lib/python3.5/dist-packages/tetherback/tetherback.py", line 344, in main
    backup_partition(adb, partmap[standard], bp, args.transport, backupdir, args.verify)
  File "/usr/local/lib/python3.5/dist-packages/tetherback/tetherback.py", line 230, in backup_partition
    raise RuntimeError("%s: don't know how to mount this partition" % pi.devname)
RuntimeError: mmcblk0p42: don't know how to mount this partition
```

**Comment by dlenski** [comment] 2017-02-13 23:26
Duplicate of #42.

**Closed as completed by dlenski** 2017-02-13 23:26 UTC
Labels: duplicate
